#!/usr/bin/env node
/**
 * Seals the seed-phrase reward.
 *
 *   node scripts/seal.mjs
 *
 * Reads scripts/phrase.txt (the answer) and scripts/reward.md (what unlocks),
 * and writes lib/challenges/sealed.json holding only salt, iv and ciphertext.
 *
 * WHY ENCRYPT RATHER THAN COMPARE
 * A boolean check ships the answer: `if (input === "a finite game...")` is
 * right there in the bundle, and so is the reward text. Encrypting with the
 * phrase as the key means neither is shipped -- there is nothing in the
 * bundle to read, and producing the reward REQUIRES producing the phrase.
 *
 * HONEST LIMITATION, stated here so nobody mistakes this for security: a
 * client-side gate is not a secret. The phrase is guessable by anyone who
 * knows the quotation, and a determined player can brute-force offline against
 * the ciphertext. This raises the floor from "open devtools" to "actually
 * solve it or actually attack it", which is the right bar for a hidden lore
 * unlock and the WRONG bar for anything load-bearing. Never gate a resource
 * this way -- resources belong on-chain.
 *
 * Both input files are gitignored on purpose. Losing them costs you the
 * ability to re-seal, not the ability to play.
 */
import { webcrypto as crypto } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** MUST match normalise() in lib/challenges/seedphrase.ts exactly. If these
 *  two drift, the correct answer stops working and nothing says why. */
function normalise(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .join(" ");
}

const phrase = normalise(readFileSync(join(here, "phrase.txt"), "utf8"));
const reward = readFileSync(join(here, "reward.md"), "utf8");
const words = phrase.split(" ");
console.log(`phrase: ${words.length} words`);

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const base = await crypto.subtle.importKey(
  "raw", new TextEncoder().encode(phrase), "PBKDF2", false, ["deriveKey"],
);
const key = await crypto.subtle.deriveKey(
  { name: "PBKDF2", salt, iterations: 250_000, hash: "SHA-256" },
  base, { name: "AES-GCM", length: 256 }, false, ["encrypt"],
);
const ct = await crypto.subtle.encrypt(
  { name: "AES-GCM", iv }, key, new TextEncoder().encode(reward),
);

const b64 = (u8) => Buffer.from(u8).toString("base64");
writeFileSync(
  join(here, "..", "lib", "challenges", "sealed.json"),
  JSON.stringify({
    $comment:
      "Generated by web/scripts/seal.mjs. The reward text is NOT in this repo " +
      "in plaintext -- it is encrypted with the seed phrase as the key. " +
      "Regenerate with: node scripts/seal.mjs",
    iterations: 250000,
    salt: b64(salt),
    iv: b64(iv),
    ct: b64(new Uint8Array(ct)),
  }, null, 2) + "\n",
);
console.log("sealed -> lib/challenges/sealed.json");
